In [2]:
import numpy as np
from scipy.integrate import quad

In [3]:
try:
    import qutip
except:
    !pip install qutip
    import qutip

from qutip import *
qutip.__version__

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.3/16.3 MB 64.1 MB/s eta 0:00:00


'4.7.3'

In [10]:
#Tomamos, por simplicidad el intervalo [-1,1]
a = -1
b = 1

def f1(x):
    return 1

def f2(x):
    return np.sin(np.pi * x)

def f3(x):
    return np.cos(np.pi * x)

def f4(x):
    return np.sin(2 * np.pi * x)

def f5(x):
    return np.cos(2 * np.pi * x)

functions = [f1, f2, f3, f4, f5]

inner_products = np.zeros((len(functions), len(functions)))

# Utilizando el metodo quad() se calculan los productos punto:
for i in range(len(functions)):
    for j in range(len(functions)):
        inner_products[i, j], _ = quad(lambda x: functions[i](x) * functions[j](x), a, b)

are_orthogonal = True

for i in range(len(functions)):
    for j in range(len(functions)):
        if i != j and not np.isclose(inner_products[i, j], 0):
            are_orthogonal = False
            break


if are_orthogonal:
    print("El conjunto de funciones es ortogonal")
else:
    print("El conjunto de funciones no es ortogonal")


El conjunto de funciones es ortogonal


Verificamos cuales funciones hay que normalizar:

In [9]:
for i, func in enumerate(functions):
    integral_result, _ = quad(lambda x: func(x)**2, a, b)
    print(f"The integral of |f{i+1}(x)|^2 over [{a}, {b}] is {integral_result:.2f}")


The integral of |f1(x)|^2 over [-1, 1] is 2.00
The integral of |f2(x)|^2 over [-1, 1] is 1.00
The integral of |f3(x)|^2 over [-1, 1] is 1.00
The integral of |f4(x)|^2 over [-1, 1] is 1.00
The integral of |f5(x)|^2 over [-1, 1] is 1.00


Es suficiente con multiplicar f1 por el factor de normalizaciòn "1/(\sqrt(2))" para obtener:

In [11]:
def f1N(x):
  return 1/(np.sqrt(2))
functions[0]=f1N
for i, func in enumerate(functions):
    integral_result, _ = quad(lambda x: func(x)**2, a, b)
    print(f"The integral of |f{i+1}(x)|^2 over [{a}, {b}] is {integral_result:.2f}")


The integral of |f1(x)|^2 over [-1, 1] is 1.00
The integral of |f2(x)|^2 over [-1, 1] is 1.00
The integral of |f3(x)|^2 over [-1, 1] is 1.00
The integral of |f4(x)|^2 over [-1, 1] is 1.00
The integral of |f5(x)|^2 over [-1, 1] is 1.00


La base ahora esta ortonormalizada.

In [17]:
# Basis state
o = Qobj([[1],[0],[0],[0],[0]])
s1 = Qobj([[0],[1],[0],[0],[0]])
c1 = Qobj([[0],[0],[1],[0],[0]])
s2 = Qobj([[0],[0],[0],[1],[0]])
c2 = Qobj([[0],[0],[0],[0],[1]])

In [23]:
f1_ket = (1/np.sqrt(5))*(o+s1+c1+s2+c2)
f2_ket = (1/np.sqrt(3))*(o + s1 + c1)
f3_ket = (1/np.sqrt(2))*(s2+c2)

In [25]:
print("norma de f1=",f1_ket.norm())
print("norma de f2=",f2_ket.norm())
print("norma de f3=",f3_ket.norm())

norma de f1= 1.0
norma de f2= 1.0000000000000002
norma de f3= 0.9999999999999999


In [30]:
f1_bra = f1_ket.dag()
f2_bra = f2_ket.dag()
f3_bra = f3_ket.dag()
print('Norm f1:',np.sqrt(f1_bra.overlap(f1_ket)))
print('Norm f2: ',np.sqrt(f2_bra.overlap(f2_ket)))
print('Norm f3: ',np.sqrt(f3_bra.overlap(f3_ket)))

print('f1lf2=',f1_bra.overlap(f2_ket))
print('f1lf3=',f1_bra.overlap(f3_ket))
print('f2lf3= ',f2_bra.overlap(f3_ket))


Norm f1: (0.9999999999999999+0j)
Norm f2:  (1+0j)
Norm f3:  (0.9999999999999999+0j)
f1lf2= (0.7745966692414834+0j)
f1lf3= (0.6324555320336758+0j)
f2lf3=  0j


Aunque las funciones estan normalizadas (Se puede verificar analiticamente), los valores de las normas de f1 y f3 son muy cercanos a 1, pero no 1 debido a que las operaciones se realizan numericamente y aunque el resultado es bastante aproximado al real, no llega a ser 1. Por otro lado, unicamente f2 y f3 son ortogonales.

In [32]:
proj_o = o.proj()
proj_s1 = s1.proj()
proj_c2 = c2.proj()
print(proj_o)
print(proj_s1)
print(proj_c2)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


Estos objetos construidos son operadores.

In [36]:
print(proj_o*f2_ket)
print(proj_s1*f2_ket)
print(proj_c2*f2_ket)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.57735027]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]
Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.        ]
 [0.57735027]
 [0.        ]
 [0.        ]
 [0.        ]]
Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


El resultado obtenido son un nuevo estado "ket". En el caso de aplicar el proyector proj_c2 sobre f2_ket es 0, debido a que el estado f2_ket no tiene componentes que se puedan proyectar en el subespacio definido por proj_c2

In [38]:
print(proj_s1*proj_c2)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Notemos que este nuevo operador es 0, asi que su acciòn sobre el estado f2_ket dara como resultado el estado nulo. Esto se debe a que los proyectores de los estados de la base generan el estado nulo